services:
    db:
        image: postgres:15-alpine
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: mydb
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
            interval: 5s
            timeout: 5s
            retries: 5

    db-migrate:
        build: .
        depends_on:
            db:
                condition: service_healthy
        environment:
            DATABASE_URL: postgres://user:password@db:5432/mydb
        command: >
            sh -c "
                echo 'Waiting for database to be ready...' &&
                sleep 5 &&
                npx drizzle-kit push --dialect=postgresql --schema=./src/db/schema.ts --url=postgresql://user:password@db:5432/mydb &&
                echo 'Database migrations completed.'
            "
        restart: "no"

    app:
        build: .
        ports:
            - "3000:3000"
        environment:
            DATABASE_URL: postgres://user:password@db:5432/mydb
        restart: unless-stopped
        depends_on:
            db-migrate:
                condition: service_completed_successfully

volumes:
    db_data:
        driver: local
